### ISSUE TITLE
'sls models show' not working

### ISSUE THREAD

**Issue by flashsnake-so** [HyperBrain/serverless-models-plugin#3]
I am getting the following error:

``` sh
xxx-MacBook-Pro:serverless-famepick xxx$ sls models show
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Command not found.  Enter "serverless help" to see all available commands.
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:360:31)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by HyperBrain** [comment]
Did you install the plugin and reference it in your `s-projects.json`?
The error messages points to Serverless not loading the plugin.

Saw that you closed the issue... Did you solve it?

**Comment by flashsnake-so** [comment]
I just closed this.  The documentation in https://www.npmjs.com/package/serverless-models-plugin is not update-to-date. After I looked up the README.md in this repo. I found out I forgot to add the plugin in s-projects.json.  Thanks.

**Comment by HyperBrain** [comment]
I will release the doc updates tomorrow. Seems that it is better if the docs are synchronized.

**Comment by flashsnake-so** [comment]
Thanks a lot.
